// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/marinaaaniram/go-chat-server/internal/service.MessageService -o message_service_minimock.go -n MessageServiceMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/marinaaaniram/go-chat-server/internal/model"
)

// MessageServiceMock implements mm_service.MessageService
type MessageServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSend          func(ctx context.Context, chat *model.Message) (err error)
	funcSendOrigin    string
	inspectFuncSend   func(ctx context.Context, chat *model.Message)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mMessageServiceMockSend
}

// NewMessageServiceMock returns a mock for mm_service.MessageService
func NewMessageServiceMock(t minimock.Tester) *MessageServiceMock {
	m := &MessageServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mMessageServiceMockSend{mock: m}
	m.SendMock.callArgs = []*MessageServiceMockSendParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageServiceMockSend struct {
	optional           bool
	mock               *MessageServiceMock
	defaultExpectation *MessageServiceMockSendExpectation
	expectations       []*MessageServiceMockSendExpectation

	callArgs []*MessageServiceMockSendParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageServiceMockSendExpectation specifies expectation struct of the MessageService.Send
type MessageServiceMockSendExpectation struct {
	mock               *MessageServiceMock
	params             *MessageServiceMockSendParams
	paramPtrs          *MessageServiceMockSendParamPtrs
	expectationOrigins MessageServiceMockSendExpectationOrigins
	results            *MessageServiceMockSendResults
	returnOrigin       string
	Counter            uint64
}

// MessageServiceMockSendParams contains parameters of the MessageService.Send
type MessageServiceMockSendParams struct {
	ctx  context.Context
	chat *model.Message
}

// MessageServiceMockSendParamPtrs contains pointers to parameters of the MessageService.Send
type MessageServiceMockSendParamPtrs struct {
	ctx  *context.Context
	chat **model.Message
}

// MessageServiceMockSendResults contains results of the MessageService.Send
type MessageServiceMockSendResults struct {
	err error
}

// MessageServiceMockSendOrigins contains origins of expectations of the MessageService.Send
type MessageServiceMockSendExpectationOrigins struct {
	origin     string
	originCtx  string
	originChat string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSend *mMessageServiceMockSend) Optional() *mMessageServiceMockSend {
	mmSend.optional = true
	return mmSend
}

// Expect sets up expected params for MessageService.Send
func (mmSend *mMessageServiceMockSend) Expect(ctx context.Context, chat *model.Message) *mMessageServiceMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageServiceMockSendExpectation{}
	}

	if mmSend.defaultExpectation.paramPtrs != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by ExpectParams functions")
	}

	mmSend.defaultExpectation.params = &MessageServiceMockSendParams{ctx, chat}
	mmSend.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// ExpectCtxParam1 sets up expected param ctx for MessageService.Send
func (mmSend *mMessageServiceMockSend) ExpectCtxParam1(ctx context.Context) *mMessageServiceMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageServiceMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageServiceMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.ctx = &ctx
	mmSend.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmSend
}

// ExpectChatParam2 sets up expected param chat for MessageService.Send
func (mmSend *mMessageServiceMockSend) ExpectChatParam2(chat *model.Message) *mMessageServiceMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageServiceMockSendExpectation{}
	}

	if mmSend.defaultExpectation.params != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Expect")
	}

	if mmSend.defaultExpectation.paramPtrs == nil {
		mmSend.defaultExpectation.paramPtrs = &MessageServiceMockSendParamPtrs{}
	}
	mmSend.defaultExpectation.paramPtrs.chat = &chat
	mmSend.defaultExpectation.expectationOrigins.originChat = minimock.CallerInfo(1)

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the MessageService.Send
func (mmSend *mMessageServiceMockSend) Inspect(f func(ctx context.Context, chat *model.Message)) *mMessageServiceMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for MessageServiceMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by MessageService.Send
func (mmSend *mMessageServiceMockSend) Return(err error) *MessageServiceMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &MessageServiceMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &MessageServiceMockSendResults{err}
	mmSend.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// Set uses given function f to mock the MessageService.Send method
func (mmSend *mMessageServiceMockSend) Set(f func(ctx context.Context, chat *model.Message) (err error)) *MessageServiceMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the MessageService.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the MessageService.Send method")
	}

	mmSend.mock.funcSend = f
	mmSend.mock.funcSendOrigin = minimock.CallerInfo(1)
	return mmSend.mock
}

// When sets expectation for the MessageService.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mMessageServiceMockSend) When(ctx context.Context, chat *model.Message) *MessageServiceMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("MessageServiceMock.Send mock is already set by Set")
	}

	expectation := &MessageServiceMockSendExpectation{
		mock:               mmSend.mock,
		params:             &MessageServiceMockSendParams{ctx, chat},
		expectationOrigins: MessageServiceMockSendExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up MessageService.Send return parameters for the expectation previously defined by the When method
func (e *MessageServiceMockSendExpectation) Then(err error) *MessageServiceMock {
	e.results = &MessageServiceMockSendResults{err}
	return e.mock
}

// Times sets number of times MessageService.Send should be invoked
func (mmSend *mMessageServiceMockSend) Times(n uint64) *mMessageServiceMockSend {
	if n == 0 {
		mmSend.mock.t.Fatalf("Times of MessageServiceMock.Send mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSend.expectedInvocations, n)
	mmSend.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSend
}

func (mmSend *mMessageServiceMockSend) invocationsDone() bool {
	if len(mmSend.expectations) == 0 && mmSend.defaultExpectation == nil && mmSend.mock.funcSend == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSend.mock.afterSendCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSend.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Send implements mm_service.MessageService
func (mmSend *MessageServiceMock) Send(ctx context.Context, chat *model.Message) (err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	mmSend.t.Helper()

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(ctx, chat)
	}

	mm_params := MessageServiceMockSendParams{ctx, chat}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, &mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_want_ptrs := mmSend.SendMock.defaultExpectation.paramPtrs

		mm_got := MessageServiceMockSendParams{ctx, chat}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmSend.t.Errorf("MessageServiceMock.Send got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.chat != nil && !minimock.Equal(*mm_want_ptrs.chat, mm_got.chat) {
				mmSend.t.Errorf("MessageServiceMock.Send got unexpected parameter chat, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSend.SendMock.defaultExpectation.expectationOrigins.originChat, *mm_want_ptrs.chat, mm_got.chat, minimock.Diff(*mm_want_ptrs.chat, mm_got.chat))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("MessageServiceMock.Send got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSend.SendMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the MessageServiceMock.Send")
		}
		return (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(ctx, chat)
	}
	mmSend.t.Fatalf("Unexpected call to MessageServiceMock.Send. %v %v", ctx, chat)
	return
}

// SendAfterCounter returns a count of finished MessageServiceMock.Send invocations
func (mmSend *MessageServiceMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of MessageServiceMock.Send invocations
func (mmSend *MessageServiceMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to MessageServiceMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mMessageServiceMockSend) Calls() []*MessageServiceMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*MessageServiceMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *MessageServiceMock) MinimockSendDone() bool {
	if m.SendMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMock.invocationsDone()
}

// MinimockSendInspect logs each unmet expectation
func (m *MessageServiceMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageServiceMock.Send at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendCounter := mm_atomic.LoadUint64(&m.afterSendCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && afterSendCounter < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageServiceMock.Send at\n%s", m.SendMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageServiceMock.Send at\n%s with params: %#v", m.SendMock.defaultExpectation.expectationOrigins.origin, *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && afterSendCounter < 1 {
		m.t.Errorf("Expected call to MessageServiceMock.Send at\n%s", m.funcSendOrigin)
	}

	if !m.SendMock.invocationsDone() && afterSendCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageServiceMock.Send at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMock.expectedInvocations), m.SendMock.expectedInvocationsOrigin, afterSendCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
